### ISSUE TITLE
Author Init Error

### ISSUE THREAD

**Issue by chrhns** [irmen/Tale#30]
Whenever I use `python3 -m tale.author init story-name-here` or just `python3 author.py init story-name-here ` I wind up getting an error at the very end:

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.5/dist-packages/tale-4.1-py3.5.egg/tale/author.py", line 167, in <module>
>     run_from_cmdline(sys.argv[1:])
>   File "/usr/local/lib/python3.5/dist-packages/tale-4.1-py3.5.egg/tale/author.py", line 160, in run_from_cmdline
>     do_init(args[0])
>   File "/usr/local/lib/python3.5/dist-packages/tale-4.1-py3.5.egg/tale/author.py", line 115, in do_init
>     story_tpl = vfs["authoring/story_tpl.py"].text
>   File "/usr/local/lib/python3.5/dist-packages/tale-4.1-py3.5.egg/tale/vfs.py", line 168, in __getitem__
>     raise x
>   File "/usr/local/lib/python3.5/dist-packages/tale-4.1-py3.5.egg/tale/vfs.py", line 156, in __getitem__
>     data = loader.get_data(name)    # type: ignore
> FileNotFoundError: [Errno 2] No such file or directory: 'tale/authoring/story_tpl.py

Which is unusual to me, because I can cd into tale/authoring and access story_tpl.py 

It's all there, but it's giving a FileNotFoundError.

**Comment by chrhns** [comment]
And strangely enough, it works now.
